version: "3.8"
services:

  db:
    image: postgres:16
    container_name: academ-db
    environment:
      POSTGRES_DB: AcademBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - bot-network

  frontend:
    build: ./frontend
    container_name: academ-frontend
    ports:
      - "3000:80"
    networks:
      - bot-network
    depends_on:
      - rest-service

  rest-service:
    build:
      context: .
      dockerfile: rest-service/Dockerfile
    container_name: academ-rest
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/AcademBot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
      - rabbitmq
    networks:
      - bot-network

  node:
    build:
      context: .
      dockerfile: node/Dockerfile
    container_name: academ-node
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/AcademBot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - db
      - rabbitmq
    networks:
      - bot-network

  dispatcher:
    build:
      context: .
      dockerfile: dispatcher/Dockerfile
    container_name: academ-dispatcher
    ports:
      - "8085:8085"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - rabbitmq
    networks:
      - bot-network
    restart: unless-stopped

networks:
  bot-network:
    driver: bridge