package ru.shatskikh.entity.enums;

public enum UserState {
    IDLE,
    AWAITING_REGISTRATION,
    AWAITING_BROADCAST_CONTENT,
    AWAITING_USER_FOR_ROLE,
    AWAITING_USER_FOR_DELETE,
    AWAITING_GROUP_FOR_DELETE,
    AWAITING_FACULTY_FOR_DELETE,
    CREATING_GROUP,
    CREATING_FACULTY
}
